### ISSUE TITLE
NodeJS version 10 not supported anymore

### ISSUE THREAD

**Issue by virmrt** [aws-solutions/media2cloud-on-aws#14]
We tried to deploy it but dependencies in this deployment stack are not supported anymore, like the Lambdas want to start in Node version 10, but that is lagging behind to your current standard Lambda runtime. Error shown: 

“AWS will be deprecating Node.js 10 according to the end of life schedule provided by the community. Node.js 10 reaches end of life on April 30, 2021. After April 30, 2021 you can no longer create a Node.js 10 Lambda function. The ability to update a function will be disabled after May 28, 2021 . More information on can be found in the runtime support policy.”

Support is appreciated
Kind regards,

**Comment by tsshek** [comment]
Hi @virmrt,

We are in a process of updating M2C to Version 3 which will also update the NodeJS runtime version.
At the meantime, please checkout [v3preview](https://github.com/aws-solutions/media2cloud/tree/v3preview) branch that also contains CFN templates.

**Comment by raulmlamzn** [comment]
The solution was upgraded to nodejs v16 in v3.1.2: https://github.com/aws-solutions/media2cloud-on-aws/releases/tag/v3.1.2
