### ISSUE TITLE
Incorrect reading of a parameter in the "deploy-s3-dist.sh" script

### ISSUE THREAD

**Issue by karolmalinski** [aws-solutions/media2cloud-on-aws#20]
**Description**
The script `deploy-s3-dist.sh` reads parameter `--single-region` incorrectly. 
The parameter does not have any value, so the loop needs to pass only the key. Now it calls `shift` twice and as the result the parameters passed after that are read incorrectly.

**Current situation**
```
      -r|--single-region)
      SINGLE_REGION=true
      shift # past argument
      shift # past value
      ;;
```

**Expected behavior**
```
      -r|--single-region)
      SINGLE_REGION=true
      shift # past key
      ;;
```

Version: v3.0.0

**Comment by raulmlamzn** [comment]
Thank you for your suggestion. We have added this request to our backlog for this solution.

**Comment by e-thoman** [comment]
Thanks for letting us know - this should be fixed in the release that came out today
