### ISSUE TITLE
How add additional value in AWS Rekognition

### ISSUE THREAD

**Issue by pramodwph** [aws-solutions/media2cloud-on-aws#25]
We want to add the custom text or level after/before the initial text/label is generated by AWS Rekognition text/level detection. We also want to know AWS Rekognition text extraction only applicable only for the image and video or it also extract text from other documents like PDF, Word Document etc.

**Comment by raulmlamzn** [comment]
Thank you for your request. We've carefully considered your feedback and have decided not to include this feature in a future release.
