### ISSUE TITLE
UI Exception on Transcribe tab. Uncaught (in promise) TypeError: tracks is not iterable

### ISSUE THREAD

**Issue by rickosaws** [aws-solutions/media2cloud-on-aws#30]
**Describe the bug**
When selecting the Transcribe tab in the UI in v3.1.2 videoPreview.js throws an uncaught exception on L216

**To Reproduce**
Tested Transcribe UI functionality in stack deployed from V3.0.0. Upgraded v3.0.0 to v3.1.2 and observed the exception. 

**Expected behavior**
Transcription tab should load successfully

**Please complete the following information about the solution:**
- [X] Version: [e.g. v3.1.2]
- [X] Region: [e.g. us-east-1]
- [NO] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [YES] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [NO] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
Uncaught (in promise) TypeError: tracks is not iterable
    trackIsEnabled videoPreview.js:216
    createContent transcribeTab.js:15
    show baseAnalysisTab.js:53
    BaseTab baseTab.js:46

**Comment by dch90** [comment]
This issue has ben resolved with the release of v3.1.3
Thanks everyone for all your feedback
