### ISSUE TITLE
All the data gets lost while converting pdf to PNG

### ISSUE THREAD

**Issue by salmahass** [aws-solutions/media2cloud-on-aws#34]
While converting PDF Files to PNG Files through the ingest-document (main/ingest/document/states/run-docinfo) step function, we noticed that all the data are lost and we only left with the file layout. 

A screenshot of input PDF File: 
![Capture pdf png (2)](https://github.com/aws-solutions/media2cloud-on-aws/assets/138890357/84f7e4c8-1041-4e70-bf95-929cd079c069)

A screenshot of the output PNG image: 
![Sans titre PNG transformation](https://github.com/aws-solutions/media2cloud-on-aws/assets/138890357/65e2cd76-24ec-4b24-8a14-81cd42cd7dc2)

Can you help us with the issue? 
Edit: After Investigation, the problem  is due to pdfjs-dist version( currently the deployed version is 2.2.218), I tried to upgrade it but the lambda ingest document is always in Error.

**Comment by e-thoman** [comment]
Thanks for letting us know - this should be fixed in the release that came out today. Please let us know of any further issues!
