### ISSUE TITLE
IAM policy to deploy the project

### ISSUE THREAD

**Issue by jeremycare** [aws-solutions/media2cloud-on-aws#4]
Hi!
We're willing to implement this solution on a specific account and we don't have admin access to the account, we need to create a user policy that regroups all we need to deploy media2cloud.

Do you have an IAM policy that regroups all the permissions needed to deploy this project?

**Comment by aws-kens** [comment]
Hi @jeremycare,

I am working on the IAM policies needed to deploy the solution. Will get back to you soon.

**Comment by eggoynes** [comment]
Hello there. I am also looking for an IAM policy that can allow me to launch the product, is there an update on this. 

Thank You!

**Comment by karolmalinski** [comment]
Same here. 🙏🏻 Setting up a pipeline without this is really time-consuming.

**Comment by raulmlamzn** [comment]
Thank you everyone for your suggestions. We have added this request to our backlog for this solution.
